name = "spaces-thumbnail"
main = "src/index.ts"
compatibility_date = "2025-01-07"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

r2_buckets = [{ binding = "SPACES_BUCKET", bucket_name = "spaces-viewers" }]

browser = { binding = "BROWSER" }

routes = [
  { pattern = "spcprt.com/spaces-thumb", zone_name = "spcprt.com" },
  { pattern = "spcprt.com/spaces-thumb/*", zone_name = "spcprt.com" }
]

[vars]
SPACES_HOST = "spcprt.com"
SPACES_PATH_PREFIX = "/spaces"
